# baseURL = "https://lycheeje11y.github.io/links"
languageCode = "en"
defaultContentLanguage = "en"

title = "links lol"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "links lol"
headline = "Joseph Wu"
image = "img/author.png" # path relative to static directory

links = [
  { email = "roccowu949@gmail.com" },
  { link = "https://lycheeje11y.github.io" },
  # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  # { apple = "https://www.apple.com" },
  # { bandcamp = "https://username.bandcamp.com" },
  # { bluesky = "https://bsky.app/profile/username" },
  # { codepen = "https://codepen.io/username" },
  # { dev = "https://dev.to/username" },
  # { discord = "https://discord.gg/invitecode" },
  # { dribbble = "https://dribbble.com/username" },
  # { facebook = "https://facebook.com/username" },
  # { flickr = "https://www.flickr.com/photos/username/" },
  # { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/lycheeje11y" },
  # { gitlab = "https://gitlab.com/username" },
  # { google = "https://www.google.com/" },
  # { instagram = "https://instagram.com/username" },
  # { keybase = "https://keybase.io/username" },
  # { kickstarter = "https://www.kickstarter.com/profile/username" },
  # { lastfm = "https://last.fm/user/username" },
  # { linkedin = "https://linkedin.com/in/username" },
  # { mastodon = "https://mastodon.instance/@username" },
  # { medium = "https://medium.com/username" },
  # { microsoft = "https://www.microsoft.com/" },
  # { patreon = "https://www.patreon.com/username" },
  # { pinterest = "https://pinterest.com/username" },
  # { reddit = "https://reddit.com/user/username" },
  # { slack = "https://workspace.url/team/userid" },
  # { snapchat = "https://snapchat.com/add/username" },
  # { soundcloud = "https://soundcloud.com/username" },
  { spotify = "https://open.spotify.com/user/s1eo7l6hmpuwcdm44gc1vpys0" },
  # { stack-exchange = "https://stackexchange.com/users/userid/username" },
  { stack-overflow = "https://stackoverflow.com/users/24416492/lycheejelly" },
  # { steam = "https://steamcommunity.com/profiles/userid" },
  # { telegram = "https://t.me/username" },
  # { threads = "https://threads.com/username" },
  # { tiktok = "https://tiktok.com/@username" },
  # { tumblr = "https://username.tumblr.com" },
  # { twitch = "https://twitch.tv/username" },
  # { twitter = "https://twitter.com/username" },
  # { whatsapp = "https://wa.me/phone-number" },
  # { x = "https://x.com/username" },
  # { youtube = "https://youtube.com/username" },
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
